title: Dum3bi
url: http://dum3bi.com
description: Insert tagline here

collections:
  portfolio:

markdown: kramdown

kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
